export const WIKTIONARY_HOSTS = [
  "https://en.wiktionary.org/*",
  "https://ru.wiktionary.org/*",
  "https://uk.wiktionary.org/*",
  "https://de.wiktionary.org/*",
  "https://fr.wiktionary.org/*",
  "https://es.wiktionary.org/*",
  "https://pt.wiktionary.org/*",
  "https://zh.wiktionary.org/*",
  "https://ja.wiktionary.org/*",
  "https://ko.wiktionary.org/*",
  "https://ar.wiktionary.org/*",
  "https://hi.wiktionary.org/*",
  "https://he.wiktionary.org/*",
  "https://pl.wiktionary.org/*",
  "https://ro.wiktionary.org/*",
  "https://tr.wiktionary.org/*",
  "https://it.wiktionary.org/*",
  "https://kk.wiktionary.org/*",
  "https://lv.wiktionary.org/*",
  "https://et.wiktionary.org/*",
  "https://lt.wiktionary.org/*",
] as const;
